console.log (2>10); // false
console.log (null == undefined); // true
console.log (null === undefined); // false
console.log (null > undefined); // false
console.log (null == 0); // false
console.log (null >= 0); // true
console.log (null < 0); // false
console.log (null > 0); // false    
console.log (null <= 0); // true
console.log (undefined == 0); // false
console.log (undefined >= 0); // false
console.log (undefined < 0); // false
console.log (undefined > 0); // false
console.log (undefined <= 0); // false
console.log (undefined == null); // true
console.log ("2" == 2); // true
console.log ("2" === 2); // false
console.log ("2" > 2); // false
console.log ("2" < 2); // false
console.log ("2" == 2); // true
